# Cloud Build configuration for automated deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-tutor-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-tutor-backend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-tutor-backend:$COMMIT_SHA'

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-tutor-backend:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-tutor-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-tutor-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_NAME=AI Tutor API'
      - '--set-secrets'
      - 'FIREBASE_ADMIN_CREDENTIALS_JSON=firebase-admin-credentials:latest'
      - '--max-instances'
      - '10'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/ai-tutor-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-tutor-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
