"""
Pydantic models for the PRD-driven authoring workflow.

Workflow: generate → preview (pending in drafts) → accept/reject
Previews live directly in the curriculum_drafts document as unit entries
with authoring metadata (status, preview_id, lumina_coverage).
"""

from typing import List, Optional, Literal, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field


# ------------------------------------------------------------------ #
#  Subskill preview (what Gemini generates)
# ------------------------------------------------------------------ #

class GeneratedSubskill(BaseModel):
    """A single subskill generated by the AI."""
    subskill_id: str
    subskill_description: str
    subskill_order: int = 1
    difficulty_start: float = 1.0
    difficulty_end: float = 5.0
    target_difficulty: float = 3.0
    target_primitive: str = ""           # Lumina primitive or "ai-tutor-session"
    standards_alignment: Optional[str] = None  # e.g. "1.OA.1"


class GeneratedSkill(BaseModel):
    """A skill with its subskills, generated by the AI."""
    skill_id: str
    skill_description: str
    skill_order: int = 1
    subskills: List[GeneratedSubskill] = []


# ------------------------------------------------------------------ #
#  Lumina coverage stats
# ------------------------------------------------------------------ #

class LuminaCoverage(BaseModel):
    """How well the generated unit covers Lumina primitives."""
    total_subskills: int = 0
    primitive_targeted: int = 0          # Has a named primitive
    ai_tutor_targeted: int = 0           # Uses AI tutor session
    problem_type_targeted: int = 0       # Uses a problem-type primitive
    untargeted: int = 0                  # Failed renderability test
    coverage_pct: float = 0.0            # (targeted / total) * 100
    primitives_used: Dict[str, int] = {} # primitive_name -> count


# ------------------------------------------------------------------ #
#  Unit preview (API response model — constructed from draft data)
# ------------------------------------------------------------------ #

class UnitPreview(BaseModel):
    """A complete unit preview generated from PRD context."""
    preview_id: str
    subject_id: str
    grade: str
    unit_id: str
    unit_title: str
    unit_description: str
    unit_order: int = 1
    skills: List[GeneratedSkill] = []
    lumina_coverage: LuminaCoverage = LuminaCoverage()
    status: Literal["pending", "accepted", "rejected"] = "pending"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    accepted_at: Optional[datetime] = None
    rejected_at: Optional[datetime] = None
    rejection_feedback: Optional[str] = None


# ------------------------------------------------------------------ #
#  Request / Response models
# ------------------------------------------------------------------ #

class AuthorSubjectRequest(BaseModel):
    """Create or retrieve a subject shell for authoring."""
    subject_id: str                       # e.g. "LANGUAGE_ARTS_G1"
    subject_name: str                     # e.g. "Language Arts"
    grade: str                            # e.g. "1"
    description: Optional[str] = None


class AuthorSubjectResponse(BaseModel):
    """Response after creating/retrieving a subject."""
    subject_id: str
    subject_name: str
    grade: str
    version_id: str
    existing_units: List[Dict[str, Any]] = []  # Already-authored units
    message: str = ""


class AuthorUnitRequest(BaseModel):
    """Request to generate a unit from PRD context."""
    subject_id: str
    grade: str
    unit_id: str
    unit_title: str
    unit_description: str
    unit_order: int = 1
    prd_context: str                      # The PRD's skill/primitive mapping table
    custom_instructions: Optional[str] = None  # Your notes to Gemini (iterate, adjust, focus areas)
    num_skills: Optional[int] = None      # Hint for skill count
    num_subskills_per_skill: Optional[int] = None


class AuthorUnitResponse(BaseModel):
    """Response with the generated preview."""
    preview: UnitPreview
    message: str = ""


class AcceptUnitRequest(BaseModel):
    """Accept a unit preview — flips status to accepted in curriculum_drafts."""
    preview_id: str
    subject_id: str
    grade: str


class AcceptUnitResponse(BaseModel):
    """Response after accepting a unit."""
    preview_id: str
    unit_id: str
    skills_created: int
    subskills_created: int
    message: str = ""


class RejectUnitRequest(BaseModel):
    """Reject a unit preview with optional feedback for regeneration."""
    preview_id: str
    subject_id: str
    grade: str
    feedback: Optional[str] = None


class RejectUnitResponse(BaseModel):
    """Response after rejecting a unit."""
    preview_id: str
    status: str = "rejected"
    message: str = ""


class RegenerateUnitRequest(BaseModel):
    """Regenerate a rejected unit with additional feedback."""
    preview_id: str
    subject_id: str
    grade: str
    additional_feedback: Optional[str] = None
    custom_instructions: Optional[str] = None  # New instructions for regeneration


class ListPreviewsResponse(BaseModel):
    """List all previews for a subject."""
    subject_id: str
    previews: List[UnitPreview] = []
    stats: Dict[str, int] = {}           # pending, accepted, rejected counts


# ------------------------------------------------------------------ #
#  Skill-level generation (add skills to an existing unit)
# ------------------------------------------------------------------ #

class GenerateSkillRequest(BaseModel):
    """Request to generate a single skill with subskills via AI."""
    subject_id: str                       # e.g. "LANGUAGE_ARTS_G1"
    grade: str                            # e.g. "1"
    unit_id: str                          # Existing unit to append to
    skill_id: str                         # e.g. "LA001-10"
    skill_title: str                      # Short UI title, e.g. "Soft C and G"
    skill_order: Optional[int] = None     # Position in skill sequence (auto if omitted)
    num_subskills: int = 2                # How many subskills to generate
    prd_context: str                      # Prescriptive instructions for subskills
    custom_instructions: Optional[str] = None


class GenerateSkillResponse(BaseModel):
    """Response with the generated skill and its subskills."""
    skill: GeneratedSkill
    lumina_coverage: LuminaCoverage
    unit_id: str
    subject_id: str
    grade: str
    message: str = ""
