/**
 * Astronomy Catalog - Component definitions for astronomy primitives
 *
 * Contains astronomy and space science visualizations for K-5 science education.
 */

import { ComponentDefinition } from '../../../types';

export const ASTRONOMY_CATALOG: ComponentDefinition[] = [
  {
    id: 'solar-system-explorer',
    description: 'Interactive solar system model with accurate orbital mechanics, zoom controls, and planet details. Students explore planetary motion, compare sizes and distances, watch orbits in real-time, and discover facts about each celestial body. Features dynamic zoom from full system view down to individual planets, adjustable time scale to speed up orbital motion, and multiple scale modes (size-accurate, distance-accurate, hybrid) to teach the challenge of representing space at scale. Shows the habitable zone (Goldilocks zone) for astrobiology concepts. Includes all 8 planets plus optional dwarf planets (Pluto, Ceres, Eris) for advanced grades. Perfect for K-5 astronomy, NGSS space science standards, and next-generation science education. ESSENTIAL for teaching solar system structure, planetary motion, and scale of space.',
    constraints: 'Best for grades K-5. Learning progression: K (planet names, order, Earth), 1 (inner vs outer, sizes), 2 (orbits, day/year), 3 (moons, rings, AU), 4 (orbital periods, distances), 5 (Kepler\'s laws, gravity, habitable zone). K-2: Show inner planets only or use hybrid scale mode for visibility. 3-5: Include all 8 planets, dwarf planets optional for grade 5. Use initialZoom to control starting view: "inner" for K-1, "system" for 2-5. Enable showDistances and showHabitableZone for grades 3+. Increase timeScale for younger grades (faster = more engaging). Supports both free exploration and guided inquiry about planetary characteristics.'
  },
  {
    id: 'scale-comparator',
    description: 'Interactive scale comparison tool for celestial objects that helps students grasp mind-bending cosmic scales through familiar references. Students compare sizes, distances, masses, and light-travel times side-by-side, overlay familiar objects (basketball, car, football field) for context, and create scale models with "if Sun were basketball..." scenarios. Features progressive difficulty from K (Earth vs Moon) to Grade 5 (light-year calculations). Includes D3 zoom controls to explore extreme size ratios, reference object library with everyday items for visceral understanding, and dynamic ratio calculations showing "Jupiter is 11× wider than Earth". Scale model builder (Grades 4-5) enables hands-on calculation practice with interactive placement. Walk-through mode (Grades 3-5) visualizes distances with speed controls from walking to light speed. ESSENTIAL for developing spatial reasoning and scale comprehension across astronomy curriculum.',
    constraints: 'Best for grades K-5 with distinct learning progressions. K: 2-3 objects (Earth, Moon), size only, no ratios, everyday references (balls). Grade 1: 3-4 planets, size comparisons, sport ball equivalents. Grade 2: Sun emphasis, integer ratios, "Sun is 109× Earth!". Grade 3: 5-6 planets, add distance mode, walk-through feature, football field references. Grade 4: All 8 planets, scale model builder, AU units, complex calculations. Grade 5: 8+ objects including Voyager/stars, light-travel time mode, scientific notation, geographic references. Use compareType to focus learning: "size" for K-2, "distance" for 3-4, "time" for 5. Enable interactiveWalk for grades 3+. Scale model builder for grades 4-5 only. showRatios should be false for K-1, true for 2+. Always enable showFamiliarEquivalent for all grades. Reference objects auto-filtered by grade appropriateness.'
  },
  {
    id: 'day-night-seasons',
    description: 'Interactive Earth model showing how rotation creates day/night and how tilted orbit creates seasons. Critical for correcting the common misconception that seasons come from distance to Sun. Students spin Earth to see day/night terminator move, position Earth at different orbital points (equinoxes, solstices), observe how 23.5° tilt affects sunlight angle, place markers at different latitudes, track hours of daylight, and view from multiple perspectives (space north, space side, surface, sun view). Features real-time daylight hour calculations for any latitude, animated rotation and orbital motion, temperature zone visualization (tropical, temperate, polar), and parallel sun ray display. Progressive learning from K (day happens when we spin toward Sun) to Grade 5 (Arctic 24-hour daylight, latitude effects on seasons). D3-powered smooth animations with adjustable time speed. Includes guided questions to check understanding and correct misconceptions. ESSENTIAL for NGSS space science standards, addressing day/night cycle and seasonal patterns.',
    constraints: 'Best for grades K-5 with distinct learning progressions. K: Focus on day/night only, 2-3 familiar locations, simple questions ("When is it daytime?"), fast animation (8x speed), no tilt axis shown. Grade 1: Day/night emphasis, "Sun doesn\'t move—we do!", 2-3 locations, 7x speed. Grade 2: Introduce both concepts, show tilt axis, 3 locations including equator, both rotation and orbit animation. Grade 3: Seasons focus, emphasize TILT not distance, show hemisphere differences, 3-4 locations with varied latitudes, orbital animation. Grade 4: Both day/night and seasons, equinox vs solstice, temperature zones, 4-5 locations including polar region, complex questions. Grade 5: Advanced concepts (Arctic phenomena, latitude effects), all visual elements enabled, scientific questions. Set focusMode: "day-night" for K-1, "seasons" for 3, "both" for 2,4-5. Use viewPerspective: "space_side" (best for showing tilt). Enable showTiltAxis for grades 2+. Enable showTemperatureZones for grades 4-5 only. Always include markerLatitudes with VARIED latitudes (equator, mid-latitude, polar for 4-5). Initial position should match current season or learning focus. Essential for teaching that seasons are caused by tilt, NOT distance from Sun.'
  },
  {
    id: 'moon-phases-lab',
    description: 'Interactive Earth-Moon-Sun model that explains why the Moon appears to change shape through the lunar cycle. Students position Moon in orbit around Earth, view from Earth\'s surface (how Moon looks in the sky), view from space (orbital geometry showing why phases occur), match phase to orbital position, predict next phase in sequence, track full 29.5-day cycle with animation, and understand tidal locking (why same side always faces us). Features dual-view mode (Earth view + space view), smooth D3 animations of lunar orbit, interactive dragging to explore phases, illumination percentage display, day-in-cycle counter, and challenge mode to identify specific phases. Corrects common misconception that phases are caused by Earth\'s shadow (that\'s eclipses, not phases!). Progressive learning from K (Moon looks different) to Grade 5 (tidal locking, eclipse geometry). ESSENTIAL for NGSS space science standards on Moon phases and lunar cycles.',
    constraints: 'Best for grades K-5 with distinct learning progressions. K: from_earth view only, focus on "Moon looks different on different nights", no orbital diagram, fast animation (8x speed), 1-2 simple questions. Grade 1: from_earth view, introduce phase names and sequence, show phase emojis as labels. Grade 2: split_view to show Moon orbits Earth, introduce orbital path, explain ~1 month cycle. Grade 3: split_view, show sun direction arrows, emphasize geometry NOT Earth\'s shadow, match phase to position. Grade 4: split_view with all features, predict phases, introduce tidal locking concept, calculate illumination percentage. Grade 5: All features enabled, tidal locking explanation, eclipse geometry hints, scientific vocabulary. Set viewMode: "from_earth" for K-1, "split_view" for 2-5. Enable showSunDirection for grades 2+. Enable showTidalLocking for grades 4-5 only. Enable phaseLabels for all grades (use emojis for K-1, text for 2-5). Always enable interactivePosition for hands-on exploration. Use animateOrbit with cycleSpeed 8 for K-1, 5 for 2-3, 3-4 for 4-5. Optional challengePhase for assessment (ask student to find specific phase). Critical teaching point: Phases are NOT caused by Earth\'s shadow!'
  },
  {
    id: 'rocket-builder',
    description: 'Comprehensive rocket design and simulation tool where students assemble rockets from components, balance thrust and weight, and launch to see if their designs reach space. The flagship spaceflight primitive. Students select rocket stages and components (capsules, fuel tanks, engines, boosters, fins), stack stages vertically, choose engine types and fuel amounts, adjust payload, check thrust-to-weight ratio, launch and watch flight profile with real-time D3 animation, see staging events during flight, and analyze why designs succeed or fail. Features progressive difficulty from K (rockets have parts) to Grade 5 (delta-v budgets and orbit insertion). Includes budget constraints for resource management, guided mode with hints, multiple atmosphere models, and detailed flight profile graphs showing altitude, velocity, and staging events. ESSENTIAL for NGSS engineering design standards and spaceflight education.',
    constraints: 'Best for grades K-5 with distinct learning progressions. K: 1 stage, 3-5 simple components, no TWR/budget, target 10-20 km, focus on "rockets have parts". Grade 1: 1-2 stages, 5-7 components, show fuel gauge, target 20-50 km, focus on "engines use fuel". Grade 2: 2 stages, 7-10 components with mass variation, show TWR, target 50-100 km, focus on "heavy rockets need more thrust". Grade 3: 2-3 stages, 10-12 components, show forces, optional budget, target 100 km (space!), focus on staging. Grade 4: 3-4 stages, 12-15 components with Isp stats, realistic atmosphere, budget required, target 150-200 km, focus on efficiency. Grade 5: 3-5 stages, 15+ components, targetOrbit: true, full budget constraints, target orbit (200 km + velocity), focus on delta-v and orbital mechanics. Use maxStages to control complexity. Enable showTWR for grades 2+. Enable showForces for grades 3+. Use atmosphereModel: "simple" for K-3, "realistic" for 4-5. Enable guidedMode for K-3, optional for 4-5. Include budget for grades 3+ to teach resource management.'
  },
  {
    id: 'orbit-mechanics-lab',
    description: 'Interactive orbital mechanics sandbox where students discover that orbiting is falling while moving sideways, and learn how to change orbits with carefully timed burns. Students launch objects at different speeds and angles, observe resulting orbits (or crashes!), add velocity at different points to see how burns change orbit shape, raise/lower orbits with prograde/retrograde burns, and plan transfers between orbits. Features real-time physics simulation with D3 animation, velocity vector display, gravity field visualization, apogee/perigee markers, and orbital period tracking. Progressive difficulty from K (things go around and around) to Grade 5 (Hohmann transfers and orbital rendezvous). Includes challenge modes for goal-oriented learning: reach specific altitudes, circularize orbits, change to target orbits, or rendezvous with other spacecraft. Burn controls adapt by grade from simple direction pickers to prograde/retrograde maneuver planning. ESSENTIAL for teaching orbital mechanics, gravity, and spaceflight concepts.',
    constraints: 'Best for grades K-5 with distinct learning progressions. K: Focus on "things go around and around", circular motion only, no burns, no orbital vocabulary, showOrbitPath only. Grade 1: Focus on "satellites don\'t fall because they\'re fast", speed determines orbit vs crash, reach_altitude challenge, allowLaunch: true. Grade 2: High vs low orbits, circular vs elliptical shapes, showVelocityVector and showApogeePerigee enabled, reach_altitude challenge with specific height. Grade 3: Speed-orbit relationship, introduce eccentricity concept, gravityVisualization: "field_lines", allowBurns with direction_picker, circularize challenge. Grade 4: Orbital maneuvers vocabulary (prograde/retrograde), burnMode: "prograde_retrograde", showOrbitalPeriod, change_orbit challenge with maxBurns. Grade 5: Hohmann transfers, efficient orbit changes, burnMode: "prograde_retrograde" or "manual", rendezvous challenges, maxBurns constraints (3-5). Use centralBody: "earth" for K-3, add "moon" and "mars" options for 4-5. Enable gravityVisualization for grades 3+. Burn controls are critical: direction_picker for 3, prograde_retrograde for 4-5. Challenge modes provide goal-oriented learning with age-appropriate targets.'
  },
  {
    id: 'mission-planner',
    description: 'Simplified mission design tool where students plan trips to the Moon, Mars, and beyond. Students select destinations on an interactive D3 solar system map, choose launch windows based on planetary alignment, plan trajectories (direct route vs gravity assist via other planets), pack supplies for crew (food, water, oxygen), estimate travel time, calculate fuel requirements, and monitor animated mission progress. Features progressive learning phases: explore destinations, plan route and timing, prepare supplies, and launch with real-time progress tracking. Includes interactive supply calculator for food/water/oxygen planning, launch window selection showing optimal planetary alignment, gravity assist trajectory visualization, mission clock with elapsed time, and destination info panels with fun facts. D3 solar system visualization shows orbital paths, planet positions, trajectory lines, and animated spacecraft icon. Progressive difficulty from K (pick a destination!) to Grade 5 (optimize fuel vs payload trade-offs with gravity assists and tight fuel constraints). ESSENTIAL for teaching space travel concepts, mission planning, supply logistics, and interplanetary navigation for K-5 astronomy.',
    constraints: 'Best for grades K-5 with distinct learning progressions. K: 2-3 destinations (Moon, Mars), flyby mission, no trajectory/supplies/launch windows shown, focus on "we can visit other places in space". Grade 1: 3 destinations, showTrajectory enabled, missionClock enabled, focus on "different places take different times to reach". Grade 2: 3 destinations, supplyCalculator enabled with 3 items (food, water, oxygen), crewed: true, focus on "astronauts need food, water, and air". Grade 3: 4 destinations, showLaunchWindows with 3-4 options (one optimal), supplyCalculator with 4 items, focus on "can\'t launch anytime - planets move!". Grade 4: 4-5 destinations, gravityAssistOption enabled, all features active, missionType: "return", focus on "gravity assists give speed boosts from planets". Grade 5: All 5 destinations, tight fuelConstraint (30 tons), 5 supply types including science equipment, missionType: "return", focus on "trade-offs: speed vs fuel vs payload". Always provide age-appropriate hints and fun facts per destination.'
  }
];
