/**
 * Biology Catalog - Component definitions for biology primitives
 *
 * Contains biology visualization components for species information,
 * taxonomy, ecology, and life sciences content.
 */

import { ComponentDefinition } from '../../../types';

export const BIOLOGY_CATALOG: ComponentDefinition[] = [
  {
    id: 'organism-card',
    description: 'Foundational organism information card with key biological attributes - the essential "unit" of biology content. Scales from K-2 (simple attributes with icons: habitat, diet, size, locomotion) to 6-8 (full taxonomy, cellular characteristics, evolutionary context). PERFECT for classification activities, organism comparison lessons, habitat studies, and building foundational biology knowledge. Features grade-appropriate vocabulary, visual image prompts, fun facts, and configurable complexity. Use this for introducing organisms before diving deeper with species-profile. ESSENTIAL for K-8 life sciences when you need quick, accessible organism reference cards that students can compare side-by-side.',
    constraints: 'Use for K-8 students. Automatically adapts complexity based on grade level: K-2 shows only basic attributes with simple language; 3-5 adds body temperature, reproduction, and adaptations; 6-8 includes full taxonomic classification. Perfect for comparison activities, classification lessons, ecosystem studies, and building biology vocabulary. Use multiple organism-cards together for compare/contrast activities.'
  },
  {
    id: 'species-profile',
    description: 'Comprehensive species profile with detailed information including physical characteristics (height, weight, length with real-world comparisons), diet and behavior, habitat and geographic/temporal distribution, complete taxonomic classification, ecological niche, fascinating facts, and discovery history. PERFECT for dinosaur lessons, animal studies, extinct species, modern wildlife, and comparative biology. Includes AI-generated species images in natural habitats. ESSENTIAL for K-5 biology, paleontology, zoology, and natural history topics. Students love learning about T-Rex, Velociraptors, Triceratops, and other fascinating creatures with this engaging format.',
    constraints: 'Best for K-8 students learning about animals, dinosaurs, plants, or any biological species. Use for life sciences, paleontology, zoology, botany, ecology, and natural history. Ideal for teaching classification systems, adaptations, food chains, habitats, and evolutionary concepts. Works great for extinct and living species.'
  },
  {
    id: 'classification-sorter',
    description: 'Interactive drag-and-drop classification activity where students categorize organisms or characteristics into labeled bins. The CORE "is it a ___?" primitive for biology. Handles binary sorts (vertebrate/invertebrate, producer/consumer), multi-category sorts (mammal/reptile/amphibian/bird/fish, kingdoms), and property-based sorts (has bones/no bones, warm-blooded/cold-blooded, makes own food/eats food). PERFECT for teaching classification skills, taxonomic thinking, characteristic discrimination, and decision-making based on biological criteria. Includes helpful hints on incorrect placements and tracks first-attempt accuracy. Can be hierarchical (Kingdom → Phylum → Class) at grades 6-8. ESSENTIAL for K-8 biology whenever students need to practice sorting, classifying, or discriminating between organisms based on characteristics.',
    constraints: 'Use for K-8 students learning classification, taxonomy, or characteristic-based sorting. K-2: Binary sorts only (2 categories, 6-8 items, simple language). 3-5: Multi-category sorts (3-5 categories, 8-10 items, introduces scientific vocabulary). 6-8: Complex or hierarchical sorts (3-6 categories, 10-12 items, formal classification systems). Always include 1-3 "boundary case" items (platypus, bat, dolphin, penguin) that challenge student thinking. Perfect for formative assessment and skill-building. Works for any classification topic: animal classes, kingdoms, habitats, diets, adaptations, life cycles, plant types, etc.'
  },
  {
    id: 'life-cycle-sequencer',
    description: 'Interactive temporal sequencing activity where students arrange stages of a biological process in correct temporal order. The CORE "what happens next?" primitive for biology. Covers organismal life cycles (butterfly metamorphosis, frog development, plant growth, human lifecycle), cellular processes (mitosis phases, meiosis, cell cycle), and ecological cycles (water cycle, carbon cycle, nitrogen cycle, rock cycle). PERFECT for teaching temporal relationships, transformation, developmental sequences, and understanding change over time. Features drag-and-drop stage cards with visual placeholders, descriptions, durations, and transition explanations. Linear layout for developmental sequences (embryo → adult), circular layout for repeating cycles (water cycle, seasons). Shows connecting arrows with transition explanations when correct. Includes misconception traps to address common errors. ESSENTIAL for K-8 biology whenever students need to understand sequences, life stages, cycles, or temporal processes.',
    constraints: 'Use for K-8 students learning life cycles, developmental sequences, or cyclical processes. K-2: Simple linear sequences (4-6 stages, basic vocabulary, observable changes like "seed grows into plant"). 3-5: More complex linear or circular cycles (5-7 stages, scientific terms introduced, mechanisms explained like "tadpole loses tail and grows legs"). 6-8: Complex cycles with molecular details (6-8 stages, cellular/molecular mechanisms, precise scientific terminology like "chromatin condenses into chromosomes"). Linear for one-direction processes (embryo to adult), circular for repeating cycles (water cycle, cell division). Always include stage durations, transition explanations, and one common misconception with correction. Perfect for any temporal biology topic: metamorphosis, germination, human development, cellular processes, biogeochemical cycles, seasonal changes, etc.'
  },
  {
    id: 'body-system-explorer',
    description: 'Interactive layered anatomy diagram of a biological system where students toggle layers (skeletal, muscular, circulatory, etc.), click organs for detailed information, and trace pathways through systems (blood flow, nerve signals, food digestion). The PRIMARY anatomy primitive for teaching human body systems. PERFECT for teaching structure-function relationships, how organs work together, and understanding physiological processes. Features SVG-based layered body diagram with clickable organ hotspots, toggleable system layers, detailed organ function cards with fun facts, and guided pathway tracing (e.g., "Journey of a Meal" through digestive system, "Path of Blood" through circulatory system). Zoom capability for detailed regions. ESSENTIAL for grades 2-8 anatomy, physiology, and health lessons. Students explore by toggling layers to see different systems, clicking organs to learn functions, and following step-by-step pathways to understand processes.',
    constraints: 'Use for grades 2-8 anatomy and physiology lessons. Supports all major body systems: digestive, circulatory, respiratory, nervous, skeletal, muscular, immune, endocrine, reproductive, urinary. Grade 2-4: Simple vocabulary, 4-6 main organs, basic pathways (3-5 steps), familiar analogies (stomach is like a blender). Grade 5-6: Scientific terminology, 6-8 organs, moderate pathways (5-7 steps), structure-function relationships. Grade 7-8: Medical terminology, 8-10+ organs with supporting structures, complex pathways (7-10+ steps), cellular/molecular detail. Perfect for anatomy units, health education, systems thinking, and understanding how body parts work together. Works great for compare/contrast (how digestive and circulatory systems interact), process understanding (how digestion works), and building mental models of body systems.'
  },
  {
    id: 'habitat-diorama',
    description: 'A scene-based interactive ecosystem explorer presenting a habitat with clickable organisms and environmental features. The PRIMARY ecosystem primitive for biology. Students explore relationships (who eats whom, where things live, how they interact). Bridges observation (K-2: "What animals live here?") into ecology concepts (3-5: food chains) and ecosystem dynamics (6-8: trophic cascades). PERFECT for teaching food webs, ecological relationships (predation, symbiosis, competition), producer-consumer roles, and systems thinking. Features interactive organisms with detailed info cards, relationship visualization showing food web connections, environmental features (water, sunlight, shelter), and optional disruption scenarios for critical thinking. Connection mode draws arrows between organisms showing relationships. ESSENTIAL for K-8 ecology, environmental science, and habitats units. Students click organisms to learn about adaptations and roles, toggle relationships to see food webs, explore environmental features, and predict cascade effects from ecosystem disruptions.',
    constraints: 'Use for K-8 students learning about ecosystems, habitats, food chains/webs, ecological relationships, or environmental science. K-2: Simple observation with 4-5 recognizable organisms (rabbit, owl, plants), basic predator-prey relationships only, 2-3 environmental features, NO disruption scenario (too complex). Focus on "What lives here? What do they eat?" 3-5: More complex with 6-8 organisms showing full food chain (producers → primary consumers → secondary consumers), introduce symbiotic relationships (mutualism, commensalism), 3-4 environmental features, INCLUDE simple disruption scenario with 3-4 predictable effects. Students trace energy through food chain. 6-8: Complex food webs with 8-10 organisms across ALL trophic levels including decomposers, full range of relationships (predation, mutualism, commensalism, parasitism, competition), 4-5 environmental features showing abiotic-biotic interactions, REQUIRED complex disruption scenario with 4-5 cascade effects demonstrating systems thinking (trophic cascade, competitive release, population dynamics). Perfect for any ecosystem/habitat: coral reef, rainforest, desert, tundra, grassland, forest, wetland, ocean, pond. Use for teaching producers/consumers/decomposers, food chains/webs, energy flow, ecological niches, adaptations, interdependence, keystone species, and ecosystem disruption.'
  },
  {
    id: 'bio-compare-contrast',
    description: 'Side-by-side or interactive Venn diagram comparison of two biological entities (organisms, cells, organs, processes, biomes). The ESSENTIAL "how are these alike and different?" primitive for biology. Two modes: side-by-side (viewing mode with aligned attributes highlighting similarities/differences) or venn-interactive (student activity where they drag attributes into correct regions: A-only, B-only, or Both). PERFECT for teaching comparative thinking, classification discrimination, understanding adaptations, and analyzing functional differences. Works for any comparison: organisms (frog vs toad, shark vs dolphin), cells (plant vs animal, prokaryote vs eukaryote), organs (heart vs lungs, roots vs stems), processes (mitosis vs meiosis, photosynthesis vs respiration), biomes (desert vs rainforest, tundra vs taiga). Features meaningful attribute categories (structure, function, habitat, behavior, etc.), shared attributes highlighting common features, key insight explaining why the comparison matters educationally. Venn-interactive mode includes drag-and-drop evaluation with immediate feedback. ESSENTIAL for K-8 biology whenever students need to compare and contrast to understand similarities, differences, and biological concepts like adaptation, classification, and function.',
    constraints: 'Use for K-8 students learning through comparison and contrast. Works for any two biological entities that have both similarities AND meaningful differences. K-2: 4-6 attributes per entity, simple observable characteristics (size, color, where they live, what they eat), familiar comparisons (dog vs cat, tree vs flower), side-by-side mode recommended for viewing. 3-5: 6-8 attributes, introduce scientific vocabulary (warm-blooded, vertebrate, photosynthesis), functional characteristics (how it reproduces, how it moves), both modes work well. 6-8: 8-10 attributes, cellular/molecular details, evolutionary context, complex processes, venn-interactive mode excellent for formative assessment. ALWAYS ensure: (1) entities have BOTH similarities and differences (avoid comparing apples to oranges with nothing in common), (2) attributes are parallel and comparable (if comparing "diet" for entityA, compare "diet" for entityB), (3) key insight connects comparison to broader biological concepts. Perfect for: comparative anatomy, classification lessons, understanding adaptations, ecosystem comparisons, cellular processes, physiological systems. Topic can include "vs" or "versus" (e.g., "mitosis vs meiosis") or specify entityA and entityB in config.'
  },
  {
    id: 'bio-process-animator',
    description: 'Step-through animation of a biological process with narrated stages and checkpoint questions embedded at key moments. Students control playback (play, pause, step forward/back) and demonstrate comprehension by answering questions. The CORE "how does this process work?" primitive for biology. PERFECT for teaching photosynthesis, cellular respiration, digestion, blood circulation, breathing, pollination, germination, protein synthesis, DNA replication, nutrient absorption, transpiration, and any multi-step biological process. Features sequential stages with narration, visual descriptions, key molecules involved, energy transformations, duration indicators, and comprehension checkpoints that pause the animation. Includes process overview with inputs/outputs and optional chemical equations. Progress tracking with visual stage indicators. Students advance through stages at their own pace and must answer checkpoint questions correctly to demonstrate understanding before continuing. ESSENTIAL for grades 2-8 biology whenever students need to understand sequential processes, mechanisms, and cause-and-effect relationships in living systems.',
    constraints: 'Use for grades 2-8 students learning multi-step biological processes. Grade 2-4: Simple vocabulary, 3-5 stages, basic comprehension checkpoints ("What happens next?", "What is produced?"), minimal molecular details, focus on observable changes. Grade 5-6: Scientific terminology introduced with explanations, 4-6 stages, causal understanding checkpoints ("Why does this happen?", "What is the purpose of X?"), introduce molecular concepts (ATP, glucose, oxygen), include energy transformations. Grade 7-8: Advanced scientific terminology, 5-8 stages, application and synthesis checkpoints ("What would happen if X was removed?", "How does this relate to Y?"), full molecular/cellular details, chemical equations, precise mechanisms. ALWAYS include: (1) clear stage-by-stage narration, (2) 1-3 checkpoint questions at strategic moments, (3) inputs and outputs of the process, (4) visual descriptions for each stage. Scale options: molecular (biochemical reactions), cellular (processes within cells), organ (organ system processes), organism (whole organism processes), ecosystem (environmental processes). Perfect for: photosynthesis, cellular respiration, digestion, circulation, transpiration, germination, protein synthesis, DNA replication, mitosis, meiosis, any sequential biological process. Works well paired with life-cycle-sequencer for developmental sequences or with body-system-explorer for organ-level processes.'
  },
  {
    id: 'microscope-viewer',
    description: 'Simulated microscope experience with zoom levels, structure labeling tasks, and guided observation prompts. Students examine specimens at increasing magnification (40x, 100x, 400x) through a circular lens viewport, identify and label structures at each level, and respond to observation questions. The PRIMARY "what do you see under the microscope?" primitive for biology. PERFECT for teaching cell biology (plant cells, animal cells, bacteria), tissue types (muscle, epithelial), microorganisms (paramecium, amoeba, euglena), and mineral structures. Bridges the gap between macro observation and micro understanding. Features per-zoom structure hotspots, drag-to-label interaction, guided observation prompts, AI-generated microscope images, and evaluation tracking for labeling accuracy and observation quality. ESSENTIAL for grades 3-8 whenever students need to develop microscopy skills, learn cell structure, practice scientific observation, or understand biological organization at different scales.',
    constraints: 'Use for grades 3-8 students learning cell biology, microscopy, tissue types, or microorganisms. Grade 3-5: Simple vocabulary, 2-3 zoom levels, 2-4 structures per level, focus on observable features and shapes. Grade 6-8: Scientific terminology, 3-4 zoom levels, 3-6 structures per level including organelles, precise descriptions, structure-function connections. Works for any microscope-observable specimen: onion cells, cheek cells, blood cells, elodea, paramecium, amoeba, bacteria, muscle tissue, leaf cross-sections, mineral crystals. Perfect for teaching: cell structure, plant vs animal cells, microscope technique, scientific observation and recording, structure-function relationships.'
  },
];
