// @vitest-environment jsdom
import React from 'react';
import { cleanup } from '@testing-library/react';
import { afterEach, describe, it, vi } from 'vitest';
import fixtures from './testing/workspaceFixtures.json';
import { expectClassicWorkspace, mountWithStore } from './testing/classicSurface';
import MissionPlanner from '../primitives/visual-primitives/astronomy/MissionPlanner';
import RocketBuilder from '../primitives/visual-primitives/astronomy/RocketBuilder';
import GravityDropTower from '../primitives/visual-primitives/physics/GravityDropTower';
import MotionDiagram from '../primitives/visual-primitives/physics/MotionDiagram';
import RaceTrackLab from '../primitives/visual-primitives/physics/RaceTrackLab';
import SoundWaveExplorer from '../primitives/visual-primitives/physics/SoundWaveExplorer';
import BridgeBuilder from '../primitives/visual-primitives/engineering/BridgeBuilder';
import TowerStacker from '../primitives/visual-primitives/engineering/TowerStacker';
import ShapeStrengthTester from '../primitives/visual-primitives/engineering/ShapeStrengthTester';
import TransportChallenge from '../primitives/visual-primitives/engineering/TransportChallenge';
import DumpTruckLoader from '../primitives/visual-primitives/engineering/DumpTruckLoader';
import ExcavatorArmSimulator from '../primitives/visual-primitives/engineering/ExcavatorArmSimulator';
import HydraulicsLab from '../primitives/visual-primitives/engineering/HydraulicsLab';
import ConstructionSequencePlanner from '../primitives/visual-primitives/engineering/ConstructionSequencePlanner';
import FoundationBuilder from '../primitives/visual-primitives/engineering/FoundationBuilder';
import AirfoilLab from '../primitives/visual-primitives/engineering/AirfoilLab';
import FlightForcesExplorer from '../primitives/visual-primitives/engineering/FlightForcesExplorer';
import PaperAirplaneDesigner from '../primitives/visual-primitives/engineering/PaperAirplaneDesigner';
import PropulsionLab from '../primitives/visual-primitives/engineering/PropulsionLab';
import PropulsionTimeline from '../primitives/visual-primitives/engineering/PropulsionTimeline';
import EngineExplorer from '../primitives/visual-primitives/engineering/EngineExplorer';
import VehicleComparisonLab from '../primitives/visual-primitives/engineering/VehicleComparisonLab';
import VehicleDesignStudio from '../primitives/visual-primitives/engineering/VehicleDesignStudio';
import BlueprintCanvas from '../primitives/visual-primitives/engineering/BlueprintCanvas';
import DigitalSkillsSim from '../primitives/visual-primitives/core/DigitalSkillsSim';
import FoundationExplorer from '../primitives/FoundationExplorer';
import FactFile from '../primitives/visual-primitives/core/FactFile';
import HowItWorks from '../primitives/visual-primitives/core/HowItWorks';
import TimelineExplorer from '../primitives/visual-primitives/core/TimelineExplorer';
import VocabularyExplorer from '../primitives/visual-primitives/core/VocabularyExplorer';
import { ComparisonPanel } from '../primitives/ComparisonPanel';
import { FeatureExhibit } from '../primitives/FeatureExhibit';
import ImagePanel from '../primitives/ImagePanel';
import DistributionExplorer from '../primitives/DistributionExplorer';
import TapeDiagram from '../primitives/visual-primitives/math/TapeDiagram';

const tutor = vi.hoisted(() => ({ isAudioPlaying: false, activePrimitiveId: null as string | null }));
vi.mock('../hooks/useLuminaAI', () => ({ useLuminaAI: () => ({ sendText: vi.fn(), isConnected: false, isAIResponding: false, ...tutor }) }));
vi.mock('../evaluation', () => ({
  usePrimitiveEvaluation: () => ({ submitResult: vi.fn(), hasSubmitted: false, submittedResult: null, elapsedMs: 0, resetAttempt: vi.fn() }),
  useEvaluationContext: () => null,
}));
vi.mock('../utils/SoundManager', () => ({ SoundManager: new Proxy({}, { get: () => vi.fn() }) }));
vi.mock('../components/PhaseSummaryPanel', () => ({ default: () => <div>summary</div> }));
vi.mock('../service/geminiClient-api', () => ({ generateConceptImage: vi.fn(async () => null) }));
vi.mock('@radix-ui/react-slider', () => {
  const Pass = ({ children }: { children?: React.ReactNode }) => <>{children}</>;
  return { Root: () => <input type="range" />, Track: Pass, Range: Pass, Thumb: Pass };
});
globalThis.ResizeObserver ??= class { observe() {} unobserve() {} disconnect() {} } as unknown as typeof ResizeObserver;
globalThis.IntersectionObserver ??= class { observe() {} unobserve() {} disconnect() {} } as unknown as typeof IntersectionObserver;
HTMLCanvasElement.prototype.getContext = (() => null) as unknown as typeof HTMLCanvasElement.prototype.getContext;
afterEach(() => { cleanup(); Object.assign(tutor, { isAudioPlaying: false, activePrimitiveId: null }); });

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyPrimitive = React.ComponentType<{ data: any }>;
// Generated by the helpers during the batch drives, or by `generateComponentContent` for
// primitives that only lessons host.
const SPEAKING: Array<[string, AnyPrimitive]> = [
  ['mission-planner', MissionPlanner], ['rocket-builder', RocketBuilder], ['gravity-drop-tower', GravityDropTower],
  ['race-track-lab', RaceTrackLab], ['sound-wave-explorer', SoundWaveExplorer], ['transport-challenge', TransportChallenge],
  ['excavator-arm-simulator', ExcavatorArmSimulator], ['hydraulics-lab', HydraulicsLab],
  ['construction-sequence-planner', ConstructionSequencePlanner], ['airfoil-lab', AirfoilLab],
  ['flight-forces-explorer', FlightForcesExplorer], ['paper-airplane-designer', PaperAirplaneDesigner],
  ['propulsion-lab', PropulsionLab], ['propulsion-timeline', PropulsionTimeline], ['engine-explorer', EngineExplorer],
  ['vehicle-comparison-lab', VehicleComparisonLab], ['vehicle-design-studio', VehicleDesignStudio],
  ['digital-skills-sim', DigitalSkillsSim], ['foundation-explorer', FoundationExplorer],
  ['distribution-explorer', DistributionExplorer], ['tape-diagram', TapeDiagram],
];
const SILENT: Array<[string, AnyPrimitive]> = [
  ['motion-diagram', MotionDiagram], ['bridge-builder', BridgeBuilder], ['tower-stacker', TowerStacker],
  ['shape-strength-tester', ShapeStrengthTester], ['dump-truck-loader', DumpTruckLoader], ['foundation-builder', FoundationBuilder],
  ['blueprint-canvas', BlueprintCanvas],
];
// These open on reading (the exhibit, the image loading, the text before its check), so no dock
// or surface appears until the child reaches the checked part.
const OPENS_UNSCOPED: Array<[string, AnyPrimitive]> = [
  ['fact-file', FactFile], ['how-it-works', HowItWorks], ['timeline-explorer', TimelineExplorer],
  ['vocabulary-explorer', VocabularyExplorer], ['comparison-panel', ComparisonPanel], ['feature-exhibit', FeatureExhibit],
  ['image-panel', ImagePanel],
];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const data = (id: string): any => ({ ...(fixtures as Record<string, object>)[id], instanceId: id });

describe('engineering, physics and core primitives share one workspace with Pip', () => {
  it.each(SPEAKING)('%s keeps the workspace contract', (id, Primitive) => {
    expectClassicWorkspace({ mounted: mountWithStore(() => <Primitive data={data(id)} />), tutor, instanceId: id });
  });

  it.each(SILENT)('%s keeps the workspace contract without tutor speech', (id, Primitive) => {
    expectClassicWorkspace({ mounted: mountWithStore(() => <Primitive data={data(id)} />), tutor, instanceId: id, silent: true });
  });

  it.each(OPENS_UNSCOPED)('%s publishes nothing before the checked part', (id, Primitive) => {
    const { store, container, unmount } = mountWithStore(() => <Primitive data={data(id)} />);
    if (store.getActive()) throw new Error(`${id} published a surface on its opening view`);
    if (container.querySelector('[data-pip-dock]')) throw new Error(`${id} shows an empty dock on its opening view`);
    unmount();
  });
});
