// @vitest-environment jsdom
import React from 'react';
import { cleanup } from '@testing-library/react';
import { afterEach, describe, it, vi } from 'vitest';
import fixtures from './testing/workspaceFixtures.json';
import { expectClassicWorkspace, mountWithStore } from './testing/classicSurface';
import ArrayGrid from '../primitives/visual-primitives/math/ArrayGrid';
import MultiplicationExplorer from '../primitives/visual-primitives/math/MultiplicationExplorer';
import SkipCountingRunner from '../primitives/visual-primitives/math/SkipCountingRunner';
import RegroupingWorkbench from '../primitives/visual-primitives/math/RegroupingWorkbench';
import CoinCounter from '../primitives/visual-primitives/math/CoinCounter';
import MeasurementTools from '../primitives/visual-primitives/math/MeasurementTools';
import PercentBar from '../primitives/visual-primitives/math/PercentBar';
import RatioTable from '../primitives/visual-primitives/math/RatioTable';
import DoubleNumberLine from '../primitives/visual-primitives/math/DoubleNumberLine';
import FactorTree from '../primitives/visual-primitives/math/FactorTree';
import FunctionMachine from '../primitives/visual-primitives/math/FunctionMachine';
import EquationWorkspace from '../primitives/visual-primitives/math/EquationWorkspace';
import FormulaLab from '../primitives/visual-primitives/math/FormulaLab';
import ParameterExplorer from '../primitives/visual-primitives/math/ParameterExplorer';
import PracticeProblem from '../primitives/visual-primitives/math/PracticeProblem';
import AngleWorkshop from '../primitives/visual-primitives/math/AngleWorkshop';
import CircleExplorer from '../primitives/visual-primitives/math/CircleExplorer';
import PolygonAreaBuilder from '../primitives/visual-primitives/math/PolygonAreaBuilder';
import NetFolder from '../primitives/visual-primitives/math/NetFolder';
import TransformationLab from '../primitives/visual-primitives/math/TransformationLab';
import Histogram from '../primitives/visual-primitives/math/Histogram';
import TwoWayTable from '../primitives/visual-primitives/math/TwoWayTable';
import CoordinateGraph from '../primitives/visual-primitives/math/CoordinateGraph';
import SlopeTriangle from '../primitives/visual-primitives/math/SlopeTriangle';
import SystemsEquationsVisualizer from '../primitives/visual-primitives/math/SystemsEquationsVisualizer';
import MatrixDisplay from '../primitives/visual-primitives/math/MatrixDisplay';
import FunctionSketch from '../primitives/visual-primitives/math/FunctionSketch';
import SpatialPath from '../primitives/visual-primitives/math/SpatialPath';

const tutor = vi.hoisted(() => ({ isAudioPlaying: false, activePrimitiveId: null as string | null }));
vi.mock('../hooks/useLuminaAI', () => ({ useLuminaAI: () => ({ sendText: vi.fn(), isConnected: false, ...tutor }) }));
vi.mock('../evaluation', () => ({
  usePrimitiveEvaluation: () => ({ submitResult: vi.fn(), hasSubmitted: false, submittedResult: null, elapsedMs: 0, resetAttempt: vi.fn() }),
  useEvaluationContext: () => null,
}));
vi.mock('../utils/SoundManager', () => ({ SoundManager: new Proxy({}, { get: () => vi.fn() }) }));
vi.mock('../components/PhaseSummaryPanel', () => ({ default: () => <div>summary</div> }));
vi.mock('../components/scratch-pad/WhiteboardCanvas', async (original) => ({
  ...(await original<object>()),
  WhiteboardCanvas: React.forwardRef(() => <canvas />),
}));
// jsdom's CSS parser rejects the Radix slider thumb's inline calc(); a range input stands in.
vi.mock('@radix-ui/react-slider', () => {
  const Pass = ({ children }: { children?: React.ReactNode }) => <>{children}</>;
  return { Root: () => <input type="range" />, Track: Pass, Range: Pass, Thumb: Pass };
});
globalThis.ResizeObserver ??= class { observe() {} unobserve() {} disconnect() {} } as unknown as typeof ResizeObserver;
afterEach(() => { cleanup(); Object.assign(tutor, { isAudioPlaying: false, activePrimitiveId: null }); });

// Generated by the math helper during the batch drives, trimmed to two challenges.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyPrimitive = React.ComponentType<{ data: any }>;
const CASES: Array<[string, AnyPrimitive]> = [
  ['array-grid', ArrayGrid], ['multiplication-explorer', MultiplicationExplorer],
  ['skip-counting-runner', SkipCountingRunner], ['regrouping-workbench', RegroupingWorkbench],
  ['coin-counter', CoinCounter], ['measurement-tools', MeasurementTools], ['percent-bar', PercentBar],
  ['ratio-table', RatioTable], ['double-number-line', DoubleNumberLine], ['factor-tree', FactorTree],
  ['function-machine', FunctionMachine], ['equation-workspace', EquationWorkspace], ['formula-lab', FormulaLab],
  ['parameter-explorer', ParameterExplorer], ['practice-problem', PracticeProblem],
  ['angle-workshop', AngleWorkshop], ['circle-explorer', CircleExplorer], ['polygon-area-builder', PolygonAreaBuilder],
  ['net-folder', NetFolder], ['transformation-lab', TransformationLab], ['histogram', Histogram], ['two-way-table', TwoWayTable],
  ['coordinate-graph', CoordinateGraph], ['slope-triangle', SlopeTriangle], ['systems-equations-visualizer', SystemsEquationsVisualizer],
  ['matrix-display', MatrixDisplay], ['function-sketch', FunctionSketch], ['spatial-path', SpatialPath],
];

describe('classic math primitives share one workspace with Pip', () => {
  it.each(CASES)('%s keeps the workspace contract', (id, Primitive) => {
    const data = { ...(fixtures as Record<string, object>)[id], instanceId: id };
    expectClassicWorkspace({ mounted: mountWithStore(() => <Primitive data={data} />), tutor, instanceId: id });
  });
});
