// @vitest-environment jsdom
import React from 'react';
import { cleanup } from '@testing-library/react';
import { afterEach, describe, it, vi } from 'vitest';
import fixtures from './testing/workspaceFixtures.json';
import { expectClassicWorkspace, mountWithStore } from './testing/classicSurface';
import RampLab from '../primitives/visual-primitives/engineering/RampLab';
import LightShadowLab from '../primitives/visual-primitives/astronomy/LightShadowLab';
import DayNightSeasons from '../primitives/visual-primitives/astronomy/DayNightSeasons';
import MoonPhasesLab from '../primitives/visual-primitives/astronomy/MoonPhasesLab';
import LifeCycleSequencer from '../primitives/visual-primitives/biology/LifeCycleSequencer';
import ClassificationSorter from '../primitives/visual-primitives/biology/ClassificationSorter';
import FoodWebBuilder from '../primitives/visual-primitives/biology/FoodWebBuilder';
import AdaptationInvestigator from '../primitives/visual-primitives/biology/AdaptationInvestigator';
import CellBuilder from '../primitives/visual-primitives/biology/CellBuilder';
import MicroscopeViewer from '../primitives/visual-primitives/biology/MicroscopeViewer';
import ProcessAnimator from '../primitives/visual-primitives/biology/ProcessAnimator';
import DnaExplorer from '../primitives/visual-primitives/biology/DnaExplorer';
import EnergyCycleEngine from '../primitives/visual-primitives/biology/EnergyCycleEngine';
import InheritanceLab from '../primitives/visual-primitives/biology/InheritanceLab';
import ProteinFolder from '../primitives/visual-primitives/biology/ProteinFolder';
import AtomBuilder from '../primitives/visual-primitives/chemistry/AtomBuilder';
import MixingAndDissolving from '../primitives/visual-primitives/chemistry/MixingAndDissolving';
import MoleculeConstructor from '../primitives/visual-primitives/chemistry/MoleculeConstructor';
import ReactionLab from '../primitives/visual-primitives/chemistry/ReactionLab';
import PhExplorer from '../primitives/visual-primitives/chemistry/PhExplorer';
import EquationBalancer from '../primitives/visual-primitives/chemistry/EquationBalancer';
import EnergyOfReactions from '../primitives/visual-primitives/chemistry/EnergyOfReactions';
import GasLawsSimulator from '../primitives/visual-primitives/chemistry/GasLawsSimulator';
import StoichiometryLab from '../primitives/visual-primitives/chemistry/StoichiometryLab';
import ConstellationBuilder from '../primitives/visual-primitives/astronomy/ConstellationBuilder';
import PlanetaryExplorer from '../primitives/visual-primitives/astronomy/PlanetaryExplorer';
import TelescopeSimulator from '../primitives/visual-primitives/astronomy/TelescopeSimulator';
import OrbitMechanicsLab from '../primitives/visual-primitives/astronomy/OrbitMechanicsLab';

const tutor = vi.hoisted(() => ({ isAudioPlaying: false, activePrimitiveId: null as string | null }));
vi.mock('../hooks/useLuminaAI', () => ({ useLuminaAI: () => ({ sendText: vi.fn(), isConnected: false, isAIResponding: false, ...tutor }) }));
vi.mock('../evaluation', () => ({
  usePrimitiveEvaluation: () => ({ submitResult: vi.fn(), hasSubmitted: false, submittedResult: null, elapsedMs: 0, resetAttempt: vi.fn() }),
  useEvaluationContext: () => null,
}));
vi.mock('../utils/SoundManager', () => ({ SoundManager: new Proxy({}, { get: () => vi.fn() }) }));
vi.mock('../components/PhaseSummaryPanel', () => ({ default: () => <div>summary</div> }));
vi.mock('../service/geminiClient-api', () => ({ generateConceptImage: vi.fn(async () => null) }));
vi.mock('@radix-ui/react-slider', () => {
  const Pass = ({ children }: { children?: React.ReactNode }) => <>{children}</>;
  return { Root: () => <input type="range" />, Track: Pass, Range: Pass, Thumb: Pass };
});
globalThis.ResizeObserver ??= class { observe() {} unobserve() {} disconnect() {} } as unknown as typeof ResizeObserver;
HTMLCanvasElement.prototype.getContext = (() => null) as unknown as typeof HTMLCanvasElement.prototype.getContext;
afterEach(() => { cleanup(); Object.assign(tutor, { isAudioPlaying: false, activePrimitiveId: null }); });

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyPrimitive = React.ComponentType<{ data: any }>;
// Generated by the science helpers during the batch drives.
const SPEAKING: Array<[string, AnyPrimitive]> = [
  ['light-shadow-lab', LightShadowLab], ['day-night-seasons', DayNightSeasons], ['moon-phases-lab', MoonPhasesLab],
  ['life-cycle-sequencer', LifeCycleSequencer], ['classification-sorter', ClassificationSorter],
  ['atom-builder', AtomBuilder], ['mixing-and-dissolving', MixingAndDissolving], ['molecule-constructor', MoleculeConstructor],
  ['ph-explorer', PhExplorer], ['equation-balancer', EquationBalancer], ['energy-of-reactions', EnergyOfReactions],
  ['gas-laws-simulator', GasLawsSimulator], ['stoichiometry-lab', StoichiometryLab],
  ['constellation-builder', ConstellationBuilder], ['orbit-mechanics-lab', OrbitMechanicsLab],
];
const SILENT: Array<[string, AnyPrimitive]> = [
  ['ramp-lab', RampLab], ['food-web-builder', FoodWebBuilder], ['adaptation-investigator', AdaptationInvestigator],
  ['cell-builder', CellBuilder], ['microscope-viewer', MicroscopeViewer], ['bio-process-animator', ProcessAnimator],
  ['dna-explorer', DnaExplorer], ['energy-cycle-engine', EnergyCycleEngine], ['telescope-simulator', TelescopeSimulator],
  ['inheritance-lab', InheritanceLab],
];
// These open on a view with nothing to answer (a reading tab, a phase before the check), so no
// surface is published until the child reaches the checked part.
const OPENS_UNSCOPED: Array<[string, AnyPrimitive]> = [
  ['protein-folder', ProteinFolder],
  ['reaction-lab', ReactionLab], ['planetary-explorer', PlanetaryExplorer],
];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const data = (id: string): any => ({ ...(fixtures as Record<string, object>)[id], instanceId: id });

describe('science primitives share one workspace with Pip', () => {
  it.each(SPEAKING)('%s keeps the workspace contract', (id, Primitive) => {
    expectClassicWorkspace({ mounted: mountWithStore(() => <Primitive data={data(id)} />), tutor, instanceId: id });
  });

  it.each(SILENT)('%s keeps the workspace contract without tutor speech', (id, Primitive) => {
    expectClassicWorkspace({ mounted: mountWithStore(() => <Primitive data={data(id)} />), tutor, instanceId: id, silent: true });
  });

  it.each(OPENS_UNSCOPED)('%s publishes nothing before the checked part', (id, Primitive) => {
    const { store, unmount } = mountWithStore(() => <Primitive data={data(id)} />);
    if (store.getActive()) throw new Error(`${id} published a surface on its opening view`);
    unmount();
  });
});
