// @vitest-environment jsdom
import React from 'react';
import { cleanup } from '@testing-library/react';
import { afterEach, beforeEach, describe, it, vi } from 'vitest';
import { mountWithStore } from './testing/classicSurface';
import { expectStimulusSurface, initialRunnerPhase, type RunnerPhase } from './testing/runnerSurface';
import fixtures from './testing/workspaceFixtures.json';
import CauseEffectChain from '../primitives/visual-primitives/history/CauseEffectChain';
import EraExplorer from '../primitives/visual-primitives/history/EraExplorer';

const phase = vi.hoisted((): RunnerPhase => ({ stage: 'asking', running: true, tutorSpeaking: false, currentSolved: false, revealHeld: false, itemIndex: 0 }));
vi.mock('../hooks/useJudgedScriptRunner', async (original) => ({
  ...(await original<object>()),
  ...(await import('./testing/runnerSurface')).fakeRunnerModule(phase as never),
}));
vi.mock('../hooks/useLuminaAI', () => ({ useLuminaAI: () => ({ sendText: vi.fn(), isConnected: false, isAudioPlaying: false }) }));
vi.mock('../components/JudgedMicPanel', () => ({ default: () => null }));
vi.mock('@/contexts/LuminaAIContext', async (original) => ({
  ...(await original<object>()),
  useLuminaAIContext: () => ({ isConnected: false, isAudioPlaying: false, sessionMode: 'idle', activePrimitiveId: null, sendText: vi.fn(), updateContext: vi.fn() }),
}));
vi.mock('../components/DiActionPanel', () => ({ default: () => null }));
vi.mock('../evaluation', () => ({
  usePrimitiveEvaluation: () => ({ submitResult: vi.fn(), hasSubmitted: false, submittedResult: null, elapsedMs: 0 }),
  useEvaluationContext: () => null,
}));
vi.mock('../utils/SoundManager', () => ({ SoundManager: new Proxy({}, { get: () => vi.fn() }) }));
vi.mock('../components/PhaseSummaryPanel', () => ({ default: () => <p>Done</p> }));
beforeEach(() => { Object.assign(phase, initialRunnerPhase()); });
afterEach(cleanup);

describe('judged primitives share their stimulus panel with Pip', () => {
  // Generated by the Language Arts helper during the batch drives.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const generated = (id: string) => ({ ...(fixtures as Record<string, any>)[id], instanceId: id });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const SCIENCE: Array<[string, React.ComponentType<{ data: any }>]> = [
    ['cause-effect-chain', CauseEffectChain], ['era-explorer', EraExplorer],
  ];
  it.each(SCIENCE)('%s outlines its stimulus panel', (id, Primitive) => {
    // The generated chain opens on a hands answer here (build the chain), which Pip receives while it is judged.
    const receive = id === 'cause-effect-chain';
    expectStimulusSurface({ mounted: mountWithStore(() => <Primitive data={generated(id)} />), phase, instanceId: id, receive });
  });
});
