import { CelestialBody } from './types';

// Simplified real data for K-5 context
export const CELESTIAL_BODIES: CelestialBody[] = [
  {
    id: 'sun',
    name: 'Sun',
    type: 'star',
    color: '#FDB813',
    radiusKm: 696340,
    distanceAu: 0,
    orbitalPeriodDays: 0,
    rotationPeriodHours: 600,
    moons: 0,
    description: "The star at the center of our Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #FDB813, #F59E0B, #B45309)',
    temperatureC: 5500
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    color: '#A5A5A5',
    radiusKm: 2439,
    distanceAu: 0.39,
    orbitalPeriodDays: 88,
    rotationPeriodHours: 1407,
    moons: 0,
    description: "The smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #E2E8F0, #94A3B8, #475569)',
    temperatureC: 167
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    color: '#E3BB76',
    radiusKm: 6051,
    distanceAu: 0.72,
    orbitalPeriodDays: 225,
    rotationPeriodHours: 5832,
    moons: 0,
    description: "The second planet from the Sun. It is named after the Roman goddess of love and beauty. Venus is the hottest planet in our solar system.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #FDE68A, #D97706, #92400E)',
    temperatureC: 464
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'planet',
    color: '#22A6B3',
    radiusKm: 6371,
    distanceAu: 1,
    orbitalPeriodDays: 365.25,
    rotationPeriodHours: 24,
    moons: 1,
    description: "Our home! Earth is the third planet from the Sun and the only astronomical object known to harbor life.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #67E8F9, #0EA5E9, #1E3A8A)',
    temperatureC: 15
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    color: '#EB4C42',
    radiusKm: 3389,
    distanceAu: 1.52,
    orbitalPeriodDays: 687,
    rotationPeriodHours: 24.6,
    moons: 2,
    description: "The fourth planet from the Sun and the second-smallest planet in the Solar System. It is often referred to as the 'Red Planet'.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #FCA5A5, #EF4444, #991B1B)',
    temperatureC: -65
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    color: '#D4A373',
    radiusKm: 69911,
    distanceAu: 5.2,
    orbitalPeriodDays: 4333,
    rotationPeriodHours: 9.9,
    moons: 95,
    description: "The fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined.",
    textureGradient: 'repeating-linear-gradient(45deg, #D6D3D1 0px, #D6D3D1 10px, #A8A29E 10px, #A8A29E 20px, #78716C 20px, #78716C 30px)',
    temperatureC: -110
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    color: '#E0C097',
    radiusKm: 58232,
    distanceAu: 9.58,
    orbitalPeriodDays: 10759,
    rotationPeriodHours: 10.7,
    moons: 146,
    description: "The sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth. Famous for its rings.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #FEF3C7, #D4D4D4, #78716C)',
    temperatureC: -140
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    color: '#7DE3F4',
    radiusKm: 25362,
    distanceAu: 19.22,
    orbitalPeriodDays: 30687,
    rotationPeriodHours: 17.2,
    moons: 27,
    description: "The seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #A5F3FC, #22D3EE, #0891B2)',
    temperatureC: -195
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    color: '#3E54E8',
    radiusKm: 24622,
    distanceAu: 30.05,
    orbitalPeriodDays: 60190,
    rotationPeriodHours: 16.1,
    moons: 14,
    description: "The eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #93C5FD, #3B82F6, #1E40AF)',
    temperatureC: -200
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'dwarf-planet',
    color: '#E8D5B5',
    radiusKm: 1188,
    distanceAu: 39.48,
    orbitalPeriodDays: 90560,
    rotationPeriodHours: 153.3,
    moons: 5,
    description: "A dwarf planet in the Kuiper belt, a ring of bodies beyond the orbit of Neptune. It was the first and the largest Kuiper belt object to be discovered.",
    textureGradient: 'radial-gradient(circle at 30% 30%, #F5F5F4, #D6D3D1, #78716C)',
    temperatureC: -225
  }
];
